using System;
namespace Application
{
    public class  PROBLEM42
    {
        public static void solution()
        {
           // Console.WriteLine("Enter the value of a: ");
          //  int a = Int32.Parse(Console.ReadLine());

           // Console.WriteLine("Enter the value of b: ");
            //int b = Int32.Parse(Console.ReadLine());

            //string strFormat = string.Format("The value of a is {0} and the value of b is {1}", a,b);

          //  int sum = a+b;
          //  Console.WriteLine(sum);
            Console.WriteLine();
        }
    }
}
